# Generated by Django 4.2 on 2023-04-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayList',
        ),
    ]
