# Generated by Django 4.2 on 2023-06-01 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
        ('music', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addsonganddateadded',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_added', to='playlist.playlist'),
        ),
        migrations.AddField(
            model_name='addsonganddateadded',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.musicupload'),
        ),
    ]
