# Generated by Django 4.2 on 2023-04-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
        ('playlist', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateAdded',
            new_name='AddSongAndDateAdded',
        ),
    ]
