# Generated by Django 4.2 on 2023-06-01 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfit',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_feats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songfit',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_feats', to='music.musicupload'),
        ),
        migrations.AddField(
            model_name='musicupload',
            name='album',
            field=models.ManyToManyField(related_name='musics', to='music.album'),
        ),
        migrations.AddField(
            model_name='musicupload',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
