# Generated by Django 4.2 on 2023-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_like_count_music_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
