# Generated by Django 4.2 on 2023-06-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artistprofile'),
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTenSongForArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_tens', to='music.musicupload')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_tens', to='users.artistprofile')),
            ],
        ),
    ]
