# Generated by Django 4.2 on 2023-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_cover_music_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs_number',
            field=models.IntegerField(default=0),
        ),
    ]
