# Generated by Django 4.2 on 2023-06-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artistprofile'),
        ('music', '0005_singerprofile_delete_artistnewprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptensongforartist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_tens', to='users.artistprofile'),
        ),
    ]
