# Generated by Django 4.2 on 2023-04-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_cover_alter_music_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='musics/cover/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(upload_to='musics/'),
        ),
    ]
