# Generated by Django 4.2 on 2023-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_music_cover_alter_music_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='number_heard',
            field=models.BigIntegerField(default=0),
        ),
    ]
