# Generated by Django 4.2 on 2023-06-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_toptensongforartist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptensongforartist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_tens', to='music.singerprofile'),
        ),
    ]
