# Generated by Django 4.2 on 2023-04-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_music_number_heard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='minutes',
            field=models.DurationField(default=0),
        ),
    ]
