# Generated by Django 4.2 on 2023-06-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_singerprofile_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptensongforartist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_tens', to='music.singerprofile'),
        ),
    ]
