# Generated by Django 4.2 on 2023-04-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_music_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='minutes',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
